servers.mailman: override new attribute in python3 env
Without this, evaluation ends with an error:

       error: fetchFromGitHub requires one of either `rev` or `tag` to be provided (not both).

The `tag` attribute was introduced in 0cd04d30366f52fe9dd7664fb7decf4b93b1d789.